name: Run tests

on:
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         python-version: ['3.7', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          if [ "${{ matrix.python-version }}" = "3.7" ]; then
            pip install "tutor==15.0.0" pylint black mypy types-setuptools
          else
            pip install -U tutor
          fi
          echo "Installing tutor-contrib-wordpress"
          pip install .[dev]
          echo "Enable wordpress plugin and save configuration"
          tutor plugins enable wordpress
          tutor config save
      - name: Test lint, types, and format
        run: make test
